### ISSUE TITLE
fix_and_updateブランチ ドキュメントのレビューコメント

### ISSUE THREAD

**Issue by hrsano645** [py-suruga/pycon-jp-2020-tutorial#26]
外部の方にお願いしている、ドキュメントのレビューコメントはこちらでお願いします。

当日使うチュートリアル資料（作業中のブランチ）: https://pycon-jp-2020-tutorial-slackbot.readthedocs.io/ja/fix_and_update/

## レビュー観点
- ドキュメントに記載しているPythonのコアの説明や、pytest, Sphinxの使い方で誤りがあるか。
- 細かいtypoや、単語の表記の間違い

**Comment by takanory** [comment]
https://pycon-jp-2020-tutorial-slackbot.readthedocs.io/ja/fix_and_update/prepare.html

```
pythonコマンドはシステムにPythonの実行環境が一つ入っている場合には、pythonコマンドはインストールされている実行環境のPythonが実行されます。
```

* ↑の日本語が冗長
* 「ローカル開発環境の用意」で開発環境と仮想環境が一緒の意味っぽいので、ちょっとわかりにくそう
* PowerShellでvenv実行する前に、スクリプトの実行権限設定が必要なはず(参考: https://pycamp.pycon.jp/textbook/6_venv.html#id12)
* 事前設定多くて大変そう。みんなちゃんとやってくるのかな...

**Comment by hrsano645** [comment]
直前に無理言って申し訳なかったです。レビューありがとうございます！大変助かります。

> https://pycon-jp-2020-tutorial-slackbot.readthedocs.io/ja/fix_and_update/prepare.html
> 
> ```
> pythonコマンドはシステムにPythonの実行環境が一つ入っている場合には、pythonコマンドはインストールされている実行環境のPythonが実行されます。
> ```
> 
> * ↑の日本語が冗長

以下のように変更してみます。

```pythonコマンドは、システム内にPython実行環境が一つのみの場合、その実行環境を利用します。```

> * 「ローカル開発環境の用意」で開発環境と仮想環境が一緒の意味っぽいので、ちょっとわかりにくそう

たしかに開発環境=仮想環境に見えてどちらかに統一したほうが良いと感じました。
Pythonのvenvの説明なので、「仮想環境の用意」に統一して、「開発環境」という言葉は外してみます。

> * PowerShellでvenv実行する前に、スクリプトの実行権限設定が必要なはず(参考: https://pycamp.pycon.jp/textbook/6_venv.html#id12)

この設定忘れてました。参考にあるpycampの権限設定のコマンドを追加します。

> * 事前設定多くて大変そう。みんなちゃんとやってくるのかな...

その通りで、こればっかりはこちらも期待するしかないかなと...
一応30分前にprepareを細かく扱う時間にして、心配な方は参加するようPyCon JPスタッフさんにアナウンスをお願いしています。

**Comment by hrsano645** [comment]
チュートリアル終了しました。レビューありがとうございます。
